- tests updated for client version 0.0.7 - Dockerfile updated to update pip and setuptools

diff --git a/tests/01-initialize-wallet-and-set-role b/tests/01-initialize-wallet-and-set-role
--- a/tests/01-initialize-wallet-and-set-role
+++ b/tests/01-initialize-wallet-and-set-role
@@ -2,48 +2,53 @@
 
 source $(dirname $0)/functions
 
+header "environment info"
+vsw --version
+echo Running on $(tty)
+echo "-"
+
 # create user 1
 
 USER1="user1"
 PASS1="$(pwgen)"
 
-# setup a new wallet and a wallet key, and
-# extract DID and verkey
+header "vsw-setup with timeout"
 
-header "Setting up wallet for $USER1"
-
-RESP="$(echo $PASS1 | vsw setup -n $USER1 -p)" &
-waitfor 30 $! || fail "wallet setup failed, error $?"
-
+RESP="$(echo $PASS1 | timeout --foreground 10 vsw setup -n $USER1 -p)"
+r=$?
+echo "Result  : $r"
+echo "Response: $RESP"
 DID1="$(echo "$RESP" | grep -e "^Created new public DID:" | cut -d " " -f 5)"
 VER1="$(echo "$RESP" | grep "^Verkey: " | cut -d " " -f 2)"
 
 [[ "${DID1:-}" != "" ]] || fail "empty DID"
 [[ "${VER1:-}" != "" ]] || fail "empty verkey"
 
-# TODO: check DID and verkey validity
+echo "DID1    : $DID1"
+echo "-"
 
-# register with sovrin
+header "registering $USER1 with sovrin"
 
-header "Registering $USER1 with sovrin"
-
-curl \
+RESP="$(curl \
+	--silent \
 	--header "Content-Type: application/json" \
 	--request POST \
 	--data "{\"network\":\"buildernet\",\"did\":\"$DID1\",\"verkey\":\"$VER1\",\"paymentaddr\":\"\"}" \
-	https://selfserve.sovrin.org/nym
+	https://selfserve.sovrin.org/nym)"
+r=$?
 
-# TODO: curl response check
+[[ $r == 0 ]] || fail "curl fails with error code $r"
 
-# run setup again
+STATUS="$(echo $RESP | jq .statusCode)"
 
-header "Re-running wallet setup for $USER1"
+[[ $STATUS == 200 ]] && echo "Registration successful." || { echo $RESP ; fail "registration failed, status $STATUS" ; }
+echo "-"
 
+header "running vsw setup again"
+
+#RESP="$(echo $PASS1 | timeout --foreground --signal=SIGHUP --kill-after=5 50 vsw setup -n $USER1)" &
 RESP="$(echo $PASS1 | vsw setup -n $USER1)" &
-waitfor 60 $! || fail "vsw re-setup timed out"
+waitfor 60 $! || fail "re-setup timed out"
 
-echo Response:
-echo
-echo "$RESP"
-
-
+exit 1
+exit $r
