Tests updated, split more, rearranged, changed to handle subshell behavior that caused earlier problems, and updated the vsw client version used to test.

diff --git a/tests/02-create-connection-and-credential-definition b/tests/02-create-connection-and-credential-definition
--- a/tests/02-create-connection-and-credential-definition
+++ b/tests/02-create-connection-and-credential-definition
@@ -10,23 +10,23 @@ header "Opening wallet (90 sec timeout)"
 
 echo Pass ${pass[1]:0:10} ...
 
-RESP="$(echo ${pass[1]} | vsw setup -n user1)" &
-waitfor 90 $! || fail "opening wallet timed out after 90 seconds, error $?"
+echo ${pass[1]} | timeout --foreground -k 2 90 vsw setup -n user1 -pn 7060,7061,7062
+r=$?
+[[ $r == 0 ]] || fail "opening wallet failed, error $?"
 
-header "Processes now:"
-ps auxw
+echo "- checking for localtunnel up"
 
-header "Netstat now:"
-netstat -na -p
+r=$(ps auxw | grep -c "node /usr/bin/npx localtunnel ")
+[[ $r == 0 ]] && fail "localtunnel not up"
+
+echo "- localtunnel started"
+
+# workaround for issue #98
+
+sleep 5
 
 header "Initializing connection"
 
 RESP="$(vsw init -c)" || fail "vsw init -c failed, error $?"
 
-#
-# create credential definition
-#
-
-header "Creating credential definition"
-
-vsw init -cd || fail "vsw init -cd failed, error $?"
+echo PASS
