- more debugging

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -42,16 +42,22 @@ jobs:
       id: commit-status
       run: |
         # Check the status of the Git commit
-        CURRENT_STATUS=$(curl --silent --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state') || { echo "curl error $?" ; exit 1 ; };
+        CURRENT_STATUS=$(curl --silent --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state')
         echo "Current status is: $CURRENT_STATUS"
-        while [ "${CURRENT_STATUS^^}" = "PENDING" ]; 
-          do sleep 10; 
-          CURRENT_STATUS=$(curl --silent --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state') || { echo "$curl error $?" ; exit 1 ; };
-        done;
-        echo "Current status is: $CURRENT_STATUS"
-        if [ "${CURRENT_STATUS^^}" = "FAILURE" ]; 
-          then echo "Commit status failed. Canceling execution"; 
-          exit 1; 
+        count=0
+        while [ "${CURRENT_STATUS^^}" = "PENDING" ]; do
+          count=$((count+1))
+          if [ $count -eq 10 ] ; then
+            echo "Maximum count exceeded, bailing out"
+            exit 1
+          fi
+          sleep 10
+          CURRENT_STATUS=$(curl --silent --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state')
+        done
+        echo "Final status is: $CURRENT_STATUS"
+        if [ "${CURRENT_STATUS^^}" = "FAILURE" ]; then
+          echo "Commit status failed. Canceling execution"
+          exit 1
         fi
         
     - name: Checkout
